void incrementHeapVariable();
void sortHeaparray(int *arr, int n);
void sort(int *arr, int n);
void readArray(int *arr, int n);
void writeArray(int *arr, int n);
char *delete(char *str, const char *substr);
char *find(const char *str, const char *substr);
int strlen(const char *str);
char *strcpy(const char *src);
char *strcat(const char *first, const char *second);
char *insert(const char *src, const char *str, int index);